### PR TITLE
Fix Firefox FOUC

### LINKED ISSUE #93: flash of unstyled content on firefox
I'm using this extension with firefox and before it shows the github page there is always a short flash of unstyled content. 

fouc

P.S. Thanks for all the great work! :)

### PR DESCRIPTION
**Pull request by fregante**
Fixes #93 

For whatever reasons, the moment you call `getBoundingClientRect` or any `offset*` properties, we get that ugly FOUC. I'd been seeing this for a long time but never thought it could be an extension causing it.

---

In Firefox only, hide overflowing items _and then,_ after a short wait (🤷‍♂️) run the calculations. 

# Test

https://github.com/babel/babel

### CODE REVIEW

File: source/hide-files-on-github.tsx [hunk 1]
```diff
@@ -21,10 +18,10 @@ function updateUI(): void {
 	}
 
 	const hidden = document.createDocumentFragment();
-	let previewList: HTMLElement | undefined;
+	let previewList: HTMLElement[] | undefined;
 
 	if (willPreviewFiles) {
-		previewList = <span className="hide-files-list"/>;
+		previewList = [];
```
Comment (fregante) [inline source/hide-files-on-github.tsx:24]: This PR also drops this unnecessary wrapper element.

**Comment by fregante** [comment]
I think I figured out why by the way: we inject the script at “document_start” and we’re forcing Firefox to give us the layout size before it’s done evaluating the style sheet. 

Chrome I guess pauses our script until the style sheet is done but Firefox just does a layout, displays it and then updates it when the CSS is ready.
